PROGRAM INOUT
    IMPLICIT NONE
    REAL :: X, Y, Z
    INTEGER :: LINE_NUM, I
    CHARACTER(LEN = 80) LINE ! PDB FILES ARE NO MORE THAN 80 COLUMNS PER LINE

    LINE_NUM = 8
    
    OPEN(UNIT=10, FILE='ethane.pdb', STATUS='OLD', ACTION='READ')

    DO I = 1, LINE_NUM
        READ(10, '(A)') LINE ! READ ENTIRE LINE
    

        READ(LINE(31:38), '(F8.3)') X ! EXPECT 3 FP DIGITS
        READ(LINE(39:46), '(F8.3)') Y ! EXPECT 3 FP DIGITS
        READ(LINE(47:54), '(F8.3)') Z ! EXPECT 3 FP DIGITS

        PRINT *, X, Y, Z
    END DO

    PRINT *, X, Y, Z
    CLOSE(10)

END PROGRAM INOUT